---
title: "SDS 192 Mini-Project 1"
subtitle: "SDS 192"
author: 
- name: Author One
  affiliation: Smith College
- name: Author Two
  affiliation: Smith College
- name: Author Three
  affiliation: Smith College
date: "`r format(Sys.Date(), '%B %e, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    fig_width: 7
    fig_height: 6
    fig_caption: true
    theme: lumen
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  echo = TRUE
)
library(tidyverse)
library(rscorecard)

sc_key("FILL API KEY HERE")
```

```{r import}
scorecard <- sc_init() %>%
  sc_year(2021) %>%                 #Note how we are looking at only 2021 data here!
  sc_filter(stabbr == "MA") %>%     #Note how we are looking at only Massachusetts data here!
  sc_select(unitid, instnm) %>%
  sc_get()
```

```{r factor}
# Example code below.
# scorecard$control_factored <- factor(scorecard$control, 
#                                      levels = c(1, 2, 3, 4),
#                                      labels = c("Public", 
#                                                 "Private nonprofit", 
#                                                 "Private for-profit", 
#                                                 "Foreign"))

# Enter your code to factor your variable here. 

```

# Univariate plot

```{r plot_1}
# Create plot 1 here
```

# Multivariate plot

```{r plot_2}
# Create plot 2 here
```

# Blog post

Compose your blog post here...



